### ISSUE TITLE
[Fix Request] 통계 목록 조회 실패 TEST 수정 요청

### ISSUE THREAD

**Issue by ZinnaChoi** [ZinnaChoi/Study-Management#73]
안녕하세요 @dayeon-dayeon 

main에서 확인한 결과 다음과 같은 에러가 발생합니다
no content 일 떄 실패 case를 만든 것 같은데 항상 content가 존재할 수 없나요? 로컬/운영 중 환경에 따라서 이는 보장되지 않을 것 같습니다 
![image](https://github.com/ZinnaChoi/Study-Management/assets/142554606/27f94e2e-9cc5-48ac-972f-78b9adb53ff1)
```
%TESTC  1 v2
%TSTTREE2,mogakco.StudyManagement.controller.StatControllerTest,true,1,false,1,StatControllerTest,,[engine:junit-jupiter]/[class:mogakco.StudyManagement.controller.StatControllerTest]
%TSTTREE3,getStatListFailPage0Size1(mogakco.StudyManagement.controller.StatControllerTest),false,1,false,2,통계 목록 조회 실패 - content가 존재하지 않음,,[engine:junit-jupiter]/[class:mogakco.StudyManagement.controller.StatControllerTest]/[method:getStatListFailPage0Size1()]
%TESTS  3,getStatListFailPage0Size1(mogakco.StudyManagement.controller.StatControllerTest)

%FAILED 3,getStatListFailPage0Size1(mogakco.StudyManagement.controller.StatControllerTest)
%TRACES 
java.lang.AssertionError: JSON path "$.retCode" expected:<404> but was:<200>
        at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
        at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:122)
        at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:123)
        at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$2(JsonPathResultMatchers.java:111)
        at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:214)
        at mogakco.StudyManagement.util.TestUtil.checkExpectedVal(TestUtil.java:75)
        at mogakco.StudyManagement.util.TestUtil.performRequest(TestUtil.java:46)
        at mogakco.StudyManagement.controller.StatControllerTest.getStatListFailPage0Size1(StatControllerTest.java:128)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

%TRACEE 

%TESTE  3,getStatListFailPage0Size1(mogakco.StudyManagement.controller.StatControllerTest)

%RUNTIME44927

```
확인 후 수정 부탁드립니다! 
감사합니다

**Comment by dayeon-dayeon** [comment]
https://github.com/ZinnaChoi/Study-Management/pull/75 에 같이 수정해서 올렸습니다 !
